name: Jaeger Release
run-name: "Jaeger Release v${{ inputs.version }}"
on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version'
        required: true
      dry-run:
        type: boolean
        description: 'Dry run'
        required: false
        default: true
      path-to-chart:
        description: 'Path to chart'
        required: true
        default: './charts/qubership-jaeger/Chart.yaml'

jobs:
  check-tag:
    runs-on: ubuntu-latest
    steps:
      - name: Check if tag exists
        id: check_tag
        uses: netcracker/qubership-workflow-hub/actions/tag-action@v2.0.6
        with:
          ref: ${{ github.ref }}
          check-tag: 'true'
          create-tag: 'false'
          tag-name: v${{ github.event.inputs.version }}

  load-docker-build-components:
    needs: [check-tag]
    runs-on: ubuntu-latest
    outputs:
      component: ${{ steps.load_component.outputs.components }}
      platforms: ${{ steps.load_component.outputs.platforms }}
    steps:
    - name: Checkout code
      uses: actions/checkout@v5

    - name: Load Docker Configuration
      id: load_component
      run:  |
        verify=$(cat "$GITHUB_WORKSPACE/.github/docker-build-config.json" | jq '
        def verify_structure:
        .components as $components
        | .platforms as $platforms
        | ($components | type == "array")
        and (all($components[]; has("name") and has("file") and has("context")))
        and ($platforms | type == "string");
        verify_structure
        | if . then true else false end
        ')
        if [ ${verify} == 'true' ]; then
          echo "✅ $GITHUB_WORKSPACE/.github/docker-build-config.json file is valid"
          components=$(jq -c ".components" "$GITHUB_WORKSPACE/.github/docker-build-config.json")
          platforms=$(jq -c ".platforms" "$GITHUB_WORKSPACE/.github/docker-build-config.json")
        else
          echo "❗ $GITHUB_WORKSPACE/.github/docker-build-config.json file is invalid"
          echo "❗ $GITHUB_WORKSPACE/.github/docker-build-config.json file is invalid" >> $GITHUB_STEP_SUMMARY
          exit 1
        fi
        echo "components=${components}" >> $GITHUB_OUTPUT
        echo "platforms=${platforms}" >> $GITHUB_OUTPUT

  prepare-tag-and-release-chart:
    permissions:
      contents: write
      packages: write
    needs: [check-tag]
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v5
      with:
        fetch-depth: 0
    - name: Release Chart
      uses: netcracker/qubership-workflow-hub/actions/charts-values-update-action@v2.0.6
      with:
        config-file: ./.github/chart-release-config.yaml
        release-version: ${{ inputs.version }}
        default-tag: ${{ inputs.version }}
        package-charts: true
        publish-charts: true
    - name: "Create release tag"
      uses: netcracker/qubership-workflow-hub/actions/tag-action@v2.0.6
      with:
        ref: "release-${{ github.event.inputs.version }}"
        check-tag: 'false'
        create-tag: 'true'
        tag-name: v${{ github.event.inputs.version }}

  github-release:
    needs: [prepare-tag-and-release-chart]
    uses: netcracker/qubership-workflow-hub/.github/workflows/release-drafter.yml@v2.0.6
    with:
      version: ${{ github.event.inputs.version }}
      publish: false

  docker-build:
    permissions:
      contents: write
      packages: write
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        component: ${{ fromJson(needs.load-docker-build-components.outputs.component) }}
    needs: [prepare-tag-and-release-chart, load-docker-build-components]
    steps:
    - name: "Docker Build"
      id: docker_build
      uses: netcracker/qubership-workflow-hub/actions/docker-action@v2.0.6
      with:
        ref: v${{ inputs.version }}
        download-artifact: false
        dry-run: ${{ inputs.dry-run }}
        component: ${{ toJson(matrix.component) }}
        platforms: ${{ needs.load-docker-build-components.outputs.platforms }}
      env:
        GITHUB_TOKEN: ${{ github.token }}

  app-manifest-build:
    runs-on: ubuntu-latest
    needs: [github-release, docker-build]
    steps:
    - name: "Configure helm"
      uses: azure/setup-helm@v4.3.0
    - name: Checkout code
      uses: actions/checkout@v5
      with:
        ref: v${{ inputs.version }}

    - name: Generate AM
      id: generate_am
      uses: borislavr/qubership-app-manifest-cli/.github/actions/app-manifest@feature/app-manifest-action
      with:
        configuration: ./.github/qubership-jaeger-am-build.yaml
        # output: ./cli/jaeger-application-manifest-v${{ inputs.version }}.json
        version: ${{ inputs.version }}
        # name: jaeger
        meta-data-files: ${{ env.META_DATA_FILES }}
        cli-version: refactoring

    - name: Upload AM to release
      uses: netcracker/qubership-workflow-hub/actions/assets-action@v2.0.6
      with:
        tag: v${{ inputs.version }}
        item-path: ${{ steps.generate_am.outputs.app-manifest-path }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
